theme: jekyll-theme-architect
title: "Laravel-VueJS Youtube Clone Project" 
description: "Web Application similar to Youtube & we can call it a Youtube Clone. This is built using Laravel Framework 6, VueJS2, MySQL, Axios"
